#
# This file is part of alfred-chrome. Copyright (C) 2016 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

[[constraint]]
  branch = "master"
  name = "howett.net/plist"

[prune]
  go-tests = true
  unused-packages = true
