combine_control_expr = false
fn_single_line = true
force_multiline_blocks = true
format_strings = true
group_imports = "StdExternalCrate"
max_width = 120
normalize_comments = true
reorder_imports = true
tab_spaces = 2
wrap_comments = true